conditional doc building, refs #12
git-svn-id: file:///home/behr_mi/git/sumo_synched/trunk@11153 afbd958f-9f77-42d5-a016-97a22340ccf4

diff --git a/sumo/tools/build/dailyUpdateMakeGCC b/sumo/tools/build/dailyUpdateMakeGCC
--- a/sumo/tools/build/dailyUpdateMakeGCC
+++ b/sumo/tools/build/dailyUpdateMakeGCC
@@ -34,16 +34,18 @@ make -f Makefile.cvs >> $MAKELOG 2>&1 || (echo "autoreconf failed" | tee -a $STA
 if make >> $MAKELOG 2>&1; then
   $PREFIX/sumo/unittest/src/sumo-unittest >> $MAKELOG 2>&1 || (echo "unit tests failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
   if make install >> $MAKELOG 2>&1; then
-    make distcheck >> $MAKELOG 2>&1 || (echo "make distcheck failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
-    if make dist-complete >> $MAKELOG 2>&1; then
-      for f in $PREFIX/sumo/sumo-*.tar.* $PREFIX/sumo/sumo-*.zip; do
-        if test $f -nt $PREFIX/sumo/configure; then
-          test -d "$NIGHTDIR" && cp $f $NIGHTDIR
-          scp -q $f $REMOTEDIR
-        fi
-      done
-    else
-      echo "make dist-complete failed" | tee -a $STATUSLOG; tail -10 $MAKELOG
+    if test -d "$NIGHTDIR"; then
+      make distcheck >> $MAKELOG 2>&1 || (echo "make distcheck failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
+      if make dist-complete >> $MAKELOG 2>&1; then
+        for f in $PREFIX/sumo/sumo-*.tar.* $PREFIX/sumo/sumo-*.zip; do
+          if test $f -nt $PREFIX/sumo/configure; then
+            cp $f $NIGHTDIR
+            scp -q $f $REMOTEDIR
+          fi
+        done
+      else
+        echo "make dist-complete failed" | tee -a $STATUSLOG; tail -10 $MAKELOG
+      fi
     fi
   else
     echo "make install failed" | tee -a $STATUSLOG; tail -10 $MAKELOG
