daily unit test ,refs #82
git-svn-id: file:///home/behr_mi/git/sumo_synched/trunk@7555 afbd958f-9f77-42d5-a016-97a22340ccf4

diff --git a/sumo/tools/build/dailyUpdateMakeGCC b/sumo/tools/build/dailyUpdateMakeGCC
--- a/sumo/tools/build/dailyUpdateMakeGCC
+++ b/sumo/tools/build/dailyUpdateMakeGCC
@@ -24,11 +24,15 @@ if test `wc -l < $MAKELOG` -le 5; then
   exit
 fi
 make -f Makefile.cvs >> $MAKELOG 2>&1 || (echo "autoreconf failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
-./configure --prefix=$PREFIX/sumo --with-fox=$PREFIX >> $MAKELOG 2>&1 || (echo "configure failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
+./configure --prefix=$PREFIX/sumo --with-fox=$PREFIX --with-gtest=$PREFIX >> $MAKELOG 2>&1 || (echo "configure failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
 if make >> $MAKELOG 2>&1; then
-  make install >> $MAKELOG 2>&1 || (echo "make install failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
-  make distcheck >> $MAKELOG 2>&1 || (echo "make distcheck failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
-  make dist-complete >> $MAKELOG 2>&1 || (echo "make dist-complete failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
+  if make install >> $MAKELOG 2>&1; then
+    make distcheck >> $MAKELOG 2>&1 || (echo "make distcheck failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
+    make dist-complete >> $MAKELOG 2>&1 || (echo "make dist-complete failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
+    sumo/bin/sumo-unittest >> $MAKELOG 2>&1 || (echo "unit tests failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
+  else
+    echo "make install failed" | tee -a $STATUSLOG; tail -10 $MAKELOG
+  fi
 else
   echo "make failed" | tee -a $STATUSLOG; tail -20 $MAKELOG
 fi
@@ -56,7 +60,7 @@ echo "--" >> $STATUSLOG
 echo `basename $MAKEALLLOG`.gz >> $STATUSLOG
 export CXXFLAGS="-Wall -W -Wfloat-equal -pedantic -Wno-long-long"
 ./configure --program-suffix=D --prefix=$PREFIX/sumo \
-  --with-fox=$PREFIX --with-proj-gdal=$PREFIX --with-gtest=$PREFIX \
+  --with-fox=$PREFIX --with-proj-gdal=$PREFIX \
   --enable-double-precision --enable-traci --enable-subsecond \
   --enable-debug --enable-memcheck --enable-messages &> $MAKEALLLOG || (echo "configure with all options failed" | tee -a $STATUSLOG; tail -10 $MAKEALLLOG)
 if make >> $MAKEALLLOG 2>&1; then
