allowing configure options in nightly build, refs #3
git-svn-id: file:///home/behr_mi/git/sumo_synched/trunk@15499 afbd958f-9f77-42d5-a016-97a22340ccf4

diff --git a/sumo/tools/build/dailyUpdateMakeGCC b/sumo/tools/build/dailyUpdateMakeGCC
--- a/sumo/tools/build/dailyUpdateMakeGCC
+++ b/sumo/tools/build/dailyUpdateMakeGCC
@@ -10,8 +10,9 @@ TESTLOG=$PREFIX/${FILEPREFIX}test.log
 export SUMO_BATCH_RESULT=$PREFIX/${FILEPREFIX}batch_result
 export SUMO_REPORT=$PREFIX/${FILEPREFIX}report
 export SUMO_BINDIR=$PREFIX/sumo/bin
-if test $# -ge 5; then
-  NIGHTDIR=$5
+CONFIGURE_OPT=$5
+if test $# -ge 6; then
+  NIGHTDIR=$6
 fi
 
 rm -f $STATUSLOG
@@ -23,16 +24,13 @@ make distclean &> /dev/null
 make -f Makefile.cvs clean &> /dev/null
 basename $MAKELOG >> $STATUSLOG
 svn up &> $MAKELOG || (echo "svn up failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
-if test `wc -l < $MAKELOG` -le 13; then # this number needs an extra +4 for every external reference
-#  echo "no changes since last run, skipping build and test"
-  exit
-fi
+SVNREV=`grep -io 'revision [0-9]*' $MAKELOG | cut -d ' ' -f 2 | tail -1`
 if test -d "$NIGHTDIR"; then
   tools/build/checkSvnProps.py
 fi
 make -f Makefile.cvs >> $MAKELOG 2>&1 || (echo "autoreconf failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
 ./configure --prefix=$PREFIX/sumo \
- --with-gtest=$PREFIX/gtest >> $MAKELOG 2>&1 || (echo "configure failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
+ --with-gtest=$PREFIX/gtest $CONFIGURE_OPT >> $MAKELOG 2>&1 || (echo "configure failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
 if make >> $MAKELOG 2>&1; then
   $PREFIX/sumo/unittest/src/sumo-unittest >> $MAKELOG 2>&1 || (echo "unit tests failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
   if make install >> $MAKELOG 2>&1; then
@@ -69,10 +67,10 @@ if test -e $SUMO_BINDIR/sumo -a $SUMO_BINDIR/sumo -nt $PREFIX/sumo/configure; th
   if test $FILEPREFIX == meso; then
     tests/runInternalTests.py "b $FILEPREFIX" &> $TESTLOG
   else
-    tests/runTests.sh -b $FILEPREFIX &> $TESTLOG
+    tests/runTests.sh -b $FILEPREFIX -name `date +%d%b%y`r$SVNREV &> $TESTLOG
   fi
   if which Xvfb &>/dev/null; then
-    tests/runTests.sh -a sumo.gui -b $FILEPREFIX >> $TESTLOG 2>&1
+    tests/runTests.sh -a sumo.gui -b $FILEPREFIX -name `date +%d%b%y`r$SVNREV >> $TESTLOG 2>&1
   fi
   tests/runTests.sh -b $FILEPREFIX -coll >> $TESTLOG 2>&1
   find $TEXTTEST_TMP -name batchreport."*" -exec echo -n '{} ' \; -exec head -1 '{}' \; | sort >> $STATUSLOG
@@ -84,7 +82,7 @@ basename $MAKEALLLOG >> $STATUSLOG
 export CXXFLAGS="-Wall -W -pedantic -Wno-long-long -Wformat -Wformat-security"
 ./configure --prefix=$PREFIX/sumo --with-python \
   --disable-double-precision --disable-subsecond --disable-internal-lanes \
-  --enable-debug --enable-memcheck &> $MAKEALLLOG || (echo "configure with all options failed" | tee -a $STATUSLOG; tail -10 $MAKEALLLOG)
+  --enable-memcheck $CONFIGURE_OPT &> $MAKEALLLOG || (echo "configure with all options failed" | tee -a $STATUSLOG; tail -10 $MAKEALLLOG)
 if make >> $MAKEALLLOG 2>&1; then
   make install >> $MAKEALLLOG 2>&1 || (echo "make install with all options failed" | tee -a $STATUSLOG; tail -10 $MAKEALLLOG)
 else
