new texttest, make doc
git-svn-id: file:///home/behr_mi/git/sumo_synched/trunk@4042 afbd958f-9f77-42d5-a016-97a22340ccf4

diff --git a/sumo/tools/build/dailyUpdateMakeGCC b/sumo/tools/build/dailyUpdateMakeGCC
--- a/sumo/tools/build/dailyUpdateMakeGCC
+++ b/sumo/tools/build/dailyUpdateMakeGCC
@@ -1,6 +1,6 @@
 #!/bin/bash
 if test "x$1" = "x"; then
-  PREFIX=$HOME/DLR
+  PREFIX=$HOME
 else
   PREFIX=$1
 fi
@@ -38,6 +38,7 @@ make -f Makefile.cvs >> $MAKELOG 2>&1 || (echo "autoreconf failed" | tee -a $STA
 --with-proj-libraries=$PREFIX/lib --with-proj-includes=$PREFIX/include \
 --prefix=$PREFIX >> $MAKELOG 2>&1 || (echo "configure failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
 make dist >> $MAKELOG 2>&1 || (echo "make dist failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
+make doc >> $MAKELOG 2>&1 || (echo "make doc failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
 make >> $MAKELOG 2>&1 || (echo "make failed" | tee -a $STATUSLOG; tail -20 $MAKELOG)
 make install >> $MAKELOG 2>&1 || (echo "make install failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
 echo `grep -c warning $MAKELOG` warnings >> $STATUSLOG
@@ -47,7 +48,7 @@ scp -q $MAKELOG.gz $REMOTEDIR
 echo "--" >> $STATUSLOG
 if test -e $PREFIX/bin/sumo -a $PREFIX/bin/sumo -nt $PREFIX/sumo/configure; then
   # run tests
-  export PATH=$PREFIX/texttest:$PATH
+  export PATH=$PREFIX/texttest/bin:$PATH
   export TEXTTEST_TMP=$PREFIX/texttesttmp
   tests/testDaily.sh $PREFIX/bin $BATCH_RESULT_DIR $REPORT_DIR $SMTP_SERVER &> /dev/null
   find $TEXTTEST_TMP -name batchreport."*" -exec echo -n '{} ' \; -exec head -1 '{}' \; | sort >> $STATUSLOG
