new gtest location, refs #22
git-svn-id: file:///home/behr_mi/git/sumo_synched/trunk@11109 afbd958f-9f77-42d5-a016-97a22340ccf4

diff --git a/sumo/tools/build/dailyUpdateMakeGCC b/sumo/tools/build/dailyUpdateMakeGCC
--- a/sumo/tools/build/dailyUpdateMakeGCC
+++ b/sumo/tools/build/dailyUpdateMakeGCC
@@ -31,7 +31,7 @@ fi
 tools/build/checkSvnProps.py
 make -f Makefile.cvs >> $MAKELOG 2>&1 || (echo "autoreconf failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
 ./configure --prefix=$PREFIX/sumo \
- --with-gtest=$PREFIX >> $MAKELOG 2>&1 || (echo "configure failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
+ --with-gtest=$PREFIX/gtest >> $MAKELOG 2>&1 || (echo "configure failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
 if make >> $MAKELOG 2>&1; then
   $PREFIX/sumo/unittest/src/sumo-unittest >> $MAKELOG 2>&1 || (echo "unit tests failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
   if make install >> $MAKELOG 2>&1; then
