small fixes to daily build
git-svn-id: file:///home/behr_mi/git/sumo_synched/trunk@9166 afbd958f-9f77-42d5-a016-97a22340ccf4

diff --git a/sumo/tools/build/dailyUpdateMakeGCC b/sumo/tools/build/dailyUpdateMakeGCC
--- a/sumo/tools/build/dailyUpdateMakeGCC
+++ b/sumo/tools/build/dailyUpdateMakeGCC
@@ -28,10 +28,10 @@ make -f Makefile.cvs >> $MAKELOG 2>&1 || (echo "autoreconf failed" | tee -a $STA
 ./configure --prefix=$PREFIX/sumo \
  --with-gtest=$PREFIX >> $MAKELOG 2>&1 || (echo "configure failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
 if make >> $MAKELOG 2>&1; then
+  $PREFIX/sumo/unittest/src/sumo-unittest >> $MAKELOG 2>&1 || (echo "unit tests failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
   if make install >> $MAKELOG 2>&1; then
     make distcheck >> $MAKELOG 2>&1 || (echo "make distcheck failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
     make dist-complete >> $MAKELOG 2>&1 || (echo "make dist-complete failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
-    $PREFIX/sumo/bin/sumo-unittest >> $MAKELOG 2>&1 || (echo "unit tests failed" | tee -a $STATUSLOG; tail -10 $MAKELOG)
   else
     echo "make install failed" | tee -a $STATUSLOG; tail -10 $MAKELOG
   fi
